name: Run Web Auto Tests

on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "ci" ]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore web-auto-test.sln

      - name: Build the solution
        run: dotnet build web-auto-test.sln --configuration Release --no-restore

      - name: Run NUnit Tests
        run: dotnet test web-auto-test.sln --no-build --verbosity normal --logger "console;verbosity=detailed"
